name: Find Rubika Chat ID

on:
  workflow_dispatch:

jobs:
  find-chat-id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Find Rubika Chat ID
        env:
          RUBIKA_TOKEN: ${{ secrets.RUBIKA_TOKEN }}
        run: |
          python get_rubika_chat_id.py
